name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: ">=2.11.0 <3.0.0"
  #sdk: '>=2.12.0 <3.0.0'

dependencies:
  bluetoothonoff: ^0.1.0
  location: ^4.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue:
    path: ../

flutter:
  uses-material-design: true
